### ISSUE TITLE
bug: new videos on channels are not appeared

### ISSUE THREAD

**Issue by QueenUlyana** [kitadai31/revanced-patches-android6-7#20] opened 2023-04-26 06:43 UTC
### Type

Error while patching

### Bug description

The new interface does not show new videos on channels. When you switch to the old interface, nothing changes. I tried older modifications and there switching to the old interface works and new videos with the old interface are shown. Correct, please.

![Screenshot_2023-04-26-07-48-34-682_app rvx android youtube](https://user-images.githubusercontent.com/83131824/234490912-d917a27f-837d-4eaf-b960-4b176bbe6b38.png)
![Screenshot_2023-04-26-07-48-52-994_app rvx android youtube](https://user-images.githubusercontent.com/83131824/234490925-a5172158-ed44-4233-8ed9-c688981d8139.png)
![Screenshot_2023-04-26-07-48-11-000_app rvx android youtube](https://user-images.githubusercontent.com/83131824/234490928-3cd0af52-8cad-4b2c-93c8-76a1056aa642.png)
![Screenshot_2023-04-26-07-47-40-821_app rvx android youtube](https://user-images.githubusercontent.com/83131824/234490931-84b84103-2b71-450a-8a0c-accc438ab6d0.png)
![Screenshot_2023-04-26-07-47-17-792_app rvx android youtube](https://user-images.githubusercontent.com/83131824/234490945-f725e21d-2b6a-409f-bf7b-f4476426c1ed.png)

### Steps to reproduce

Step 0

### Additional context

This is where I downloaded it from.
https://4pda.to/forum/index.php?showtopic=1050118&view=findpost&p=122269433

### Device Environment

Android 7.1.2 / MIUI Global 9.2.1.0 [NDAMIEK]

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment] 2023-05-01 13:09
Look at "LIVE" tab.

**Comment by QueenUlyana** [comment] 2023-05-02 17:13
> Look at "LIVE" tab. 😄

You don't understand the problem. The option that should enable the old interface and show old videos first, is NOT WORKING. In my screenshots you can see that after enabling this option nothing has changed. I am asking you to fix this.

**Comment by QueenUlyana** [comment] 2023-05-02 17:14
I can create a new topic and show you how it should be.

**Comment by kitadai31** [comment] 2023-05-03 04:41
So you are saying you want to sort the videos by oldest?
In this case, you can do it with the "Spoof app version" setting that was added in v2.160.4, released two days ago.

YouTube 17.34.36 has old layout, but does not have "sort by oldest" feature.
To use "Sort by oldest", you have to use "Spoof app version" patch and spoof to 17.06.34.

**Comment by QueenUlyana** [comment] 2023-05-03 06:38
> So you are saying you want to sort the videos by oldest? In this case, you can do it with the "Spoof app version" setting that was added in v2.160.4, released two days ago.
> 
> YouTube 17.34.36 has old layout, but does not have "sort by oldest" feature. To use "Sort by oldest", you have to use "Spoof app version" patch and spoof to 17.06.34.

Thanks more, that's just what need. Also, I noticed that RetunYouTubeDislike doesn't work, I don't get the dislikes shown on all videos. I have turned this option on and off several times, but to no avail.

**Comment by kitadai31** [comment] 2023-05-03 17:37
> Also, I noticed that RetunYouTubeDislike doesn't work

It is a side effect of spoofing to 17.06.34.

Fortunately, the original ReVanced supported RYD in 17.06.34 recently.
Perhaps I can implement it. I will try it.

**Comment by QueenUlyana** [comment] 2023-05-04 14:58
> 

No, that was before the spoofing to 17.06.34.

**Comment by kitadai31** [comment] 2023-05-04 16:54
If so I think it may have been server down of RYD.

**Comment by QueenUlyana** [comment] 2023-05-05 12:35
> If so I think it may have been server down of RYD.

I just noticed it now. When switching to version 17, I lost my video history.
![Screenshot_2023-05-05-15-28-32-287_app rvx android youtube](https://user-images.githubusercontent.com/83131824/236458818-b7e4cac6-6e4f-4c89-b1bb-83c8a7f69aa8.png)
![Screenshot_2023-05-05-15-30-41-690_app rvx android youtube](https://user-images.githubusercontent.com/83131824/236458825-adeaf82f-1894-4543-89bb-b34bdd7ed75d.png)

**Comment by kitadai31** [comment] 2023-05-21 16:54
I found it.
It is caused by "Hide braking news shelf" setting.
Please turn off temporary if you use old layout.

I will backport this inotia's update to fix this issue. https://github.com/inotia00/revanced-integrations/commit/059e5cb6202ee82fce7afd7f4872d8b5a585e767

**Comment by QueenUlyana** [comment] 2023-05-22 08:21
> I found it. It is caused by "Hide braking news shelf" setting. Please turn off temporary if you use old layout.
> 
> I will backport inotia's update to fix this issue. [inotia00/revanced-integrations@059e5cb](https://github.com/inotia00/revanced-integrations/commit/059e5cb6202ee82fce7afd7f4872d8b5a585e767)

Thanks 🙂

**Comment by QueenUlyana** [comment] 2023-05-27 10:35
@kitadai31 Hi, I found another bug. If you go to a channel that has few video clips, they will endlessly repeat and scroll.
![IMG_20230527_132847](https://github.com/kitadai31/revanced-patches-android6-7/assets/83131824/dcfec258-588e-499b-a3af-48ed53c0538b)

**Comment by QueenUlyana** [comment] 2023-05-27 10:41
Also, the history does not show "Jams" and "Playlists". I see only a white background.
![Screenshot_2023-05-27-13-35-48-429_app rvx android youtube](https://github.com/kitadai31/revanced-patches-android6-7/assets/83131824/c92b3664-ec2a-44a2-bb22-97a5e9a65f35)

**Comment by QueenUlyana** [comment] 2023-05-27 10:42
I see both of these bugs when using the 17.06.34 interface

**Comment by QueenUlyana** [comment] 2023-05-27 14:19
I also don't have a chat displayed during streams.
![Screenshot_2023-05-27-17-17-33-825_app rvx android youtube](https://github.com/kitadai31/revanced-patches-android6-7/assets/83131824/1b02964b-4355-48cf-841b-fbc02cc56096)

**Comment by kitadai31** [comment] 2023-05-27 16:30
Hello

> Hi, I found another bug. If you go to a channel that has few video clips, they will endlessly repeat and scroll.

It's server-side issue. It's reproducible even on stock 17.06.38 yt app.

> Also, the history does not show "Jams" and "Playlists". I see only a white background.

Thx. I will investigate it.

> I also don't have a chat displayed during streams.

Turn off ReVanced Settings > Layout settings > Fullscreen > Hide fullscreen panels

**Comment by kitadai31** [comment] 2024-12-01 17:08
Closing this issue because "Spoof app version" to older versions is no longer available.
https://github.com/kitadai31/revanced-patches-android6-7/wiki/Spoof-app-version-information

**Closed by kitadai31** 2024-12-01 17:08 UTC
Labels: bug
